project_id = "aqmbaycbwljiohdjputq"

[functions.parse-briefing]
verify_jwt = false

[functions.send-briefing-email]
verify_jwt = false

[functions.notify-revision]
verify_jwt = false

[functions.notify-delivery]
verify_jwt = false

[functions.suggest-briefing]
verify_jwt = false

[functions.monthly-designer-report]
verify_jwt = false

[functions.client-review-data]
verify_jwt = false

[functions.notify-meeting]
verify_jwt = false

[functions.delivery-data]
verify_jwt = false

[functions.designer-data]
verify_jwt = false